services:
  redis:
    image: redis:7
    container_name: probe-designer-redis
    networks:
      - internal_net
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: probe-designer-api
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./gene_sequences:/app/gene_sequences
      - ./probe_sequences:/app/probe_sequences
    networks:
      - internal_net
    command: uvicorn backend.main_app:app --host 0.0.0.0 --port 8002 --reload
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: probe-designer-worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - api
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./gene_sequences:/app/gene_sequences
      - ./probe_sequences:/app/probe_sequences 
    networks:
      - internal_net
    command: celery -A backend.celery_worker worker --loglevel=info
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: probe-designer-frontend
    ports:
      - "5873:80"
    volumes:
    - ./frontend/src:/app/src
    depends_on:
      - api
    networks:
      - internal_net
    restart: unless-stopped

networks:
  internal_net:
    driver: bridge
